import './js/header.js';
import './js/books-section.js';
import './js/category-list.js';
import './js/donation-block.js';
import './js/modal.js';
import './js/books-section.js';
import './js/scroll-up.js';
import './js/loader.js';
import './js/loading-bar.js';
